os: osx

env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1

script:
  - brew install awscli
  - tar czf homebrew-cache.tar.gz --directory /usr/local/Cellar awscli gdbm readline sqlite python

deploy:
  - provider: script
  - script: aws s3 sync homebrew-cache.tar.gz s3://baphomet --delete
  - skip_cleanup: true
