os: osx

env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1

before_install:
  - ./before_install.sh

install:
  - ./install.sh

script:
  - echo 'hello :)'

before_deploy:
  - ./before_deploy.sh

deploy:
  provider: s3
  bucket: baphomet
  region: $AWS_DEFAULT_REGION
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  acl: public_read
  local_dir: s3-cache
  upload-dir: travis-cache
