os: osx

env:
  global:
    HOMEBREW_NO_AUTO_UPDATE=1
    HOMEBREW_EMACS_INSTALLED="$(brew ls | grep -c emacs)"

# before_install:
#   - curl -O https://s3.amazonaws.com/baphomet/travis-cache/homebrew-cache.tar.gz
#   - tar xzf homebrew-cache.tar.gz -C /usr/local/Cellar
#   - brew link emacs gnutls

install:
  - if ! [[ $EMACS_INSTALLED -eq 1 ]]; then brew install emacs --HEAD --with-cocoa --with-gnutls; fi

script:
  - echo 'hello :)'

before_deploy:
  - tar czf homebrew-cache.tar.gz -C /usr/local/Cellar emacs gnutls
  - mkdir -p s3-cache && mv homebrew-cache.tar.gz s3-cache

deploy:
  provider: s3
  bucket: baphomet
  region: $AWS_DEFAULT_REGION
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  local_dir: s3-cache
  upload-dir: travis-cache
