os: osx

env:
  global:
    HOMEBREW_NO_AUTO_UPDATE=1

script:
  brew install nmap
  tar -czf homebrew-cache.tar.gz /usr/local/Cellar{nmap,openssl}
  mkdir -p local-cache && mv homebrew-cache.tar.gz local-cache

deploy:
  provider: s3
  bucket: baphomet
  region: $AWS_DEFAULT_REGION
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  local_dir: local-cache
