os: osx

env:
  global:
    HOMEBREW_NO_AUTO_UPDATE=1

# before_install:
#   - curl -O https://s3.amazonaws.com/baphomet/homebrew-cache.tar.gz
#   - tar xzf homebrew-cache.tar.gz -C /usr/local/Cellar
#   - brew link nmap openssl

install:
  - if ! [ -x "$(command -v nmap)" ]; then brew install nmap; fi

before_deploy:
  - tar czf homebrew-cache.tar.gz -C /usr/local/Cellar nmap openssl
  - mkdir -p s3-cache && mv homebrew-cache.tar.gz s3-cache

deploy:
  provider: s3
  bucket: baphomet
  region: $AWS_DEFAULT_REGION
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  local_dir: s3-cache
